### ISSUE TITLE
Move 'Common Provider Settings' page?

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail-docs#10]
I'm not sure about this one. Maybe we should create one post per provider in the [FAQ section of the forum](https://forum.k9mail.app/c/faq/6)? Comments welcome.

**Comment by artbristol** [comment]
I can't find anything related in the FAQ section, would you mind pointing me in the right direction please?

**Comment by cketti** [comment]
The idea was to remove `docs/accounts/provider_settings.md` from this repository. Instead we could have posts like "How to set up a Gmail account?" in the FAQ section of the forum.

**Comment by artbristol** [comment]
I can't create a new post in the FAQ section, does my `mr_art` user need extra permissions?

**Comment by cketti** [comment]
Yes. I created a new group that is allowed to posts to this category and added you to that group.
