### ISSUE TITLE
Outbox issues in airplane mode

### ISSUE THREAD

**Issue by acardona** [k9mail/k9mail-docs#104]
When sending an email while on airplane mode, K9 helpfully places it under the Outbox folder.
Upon connecting to the internet, messages aren't sent automatically, nor does K9 ask whether messages ought to be sent.
What's more, going to the Outbox and choosing "Send messages" from the 3-point menu does not send the messages at all. The only way is to send the messages to the Drafts folder, and then open each and push send: then the messages are sent successfully.
So it's not an issue with the SMTP config but with K9 itself.
Using K9 6.602 on Android.

**Comment by artbristol** [comment]
Hi, this repository is for documentation only. Please open an issue on the main code repo https://github.com/thundernest/k-9

**Comment by acardona** [comment]
Thanks. For the record: https://github.com/thundernest/k-9/issues/2898#issuecomment-1712956445
