### ISSUE TITLE
icon question

### ISSUE THREAD

**Issue by BillH99999** [k9mail/k9mail-docs#105]
Sometimes when I select one or more messages in an account inbox, I see an icon next to the hamburger menu that looks like a gray stop sign with a white exclamation mark in it.  What does that icon mean?   If I select that icon, what happens to the messages that are selected?

![Screenshot_20230926_211735_K-9 Mail](https://github.com/k9mail/k9mail-docs/assets/26846819/47260650-3a1a-4264-b2ac-992d0c850215)

Thanks,
Bill

**Comment by artbristol** [comment]
This is to move the message to a spam folder (if one is configured for the account). Long-pressing any of the icons will pop up an explanation of what it does.

Note, this repo is for issues with the documentation rather than the application itself.
