### ISSUE TITLE
k9mail cant read RTF

### ISSUE THREAD

**Issue by Li70** [k9mail/k9mail-docs#107]
Is is possible to implement in k9mail RTF (rich text format) mails in k9mail?

Users receiving mails from outlook with attachments  can't see them. Attachments are in winmail.dat format.
I remember being able to open simple .doc files in the past.
best regards,
Li70

**Comment by artbristol** [comment]
Hi, this repository is for the K-9 mail documentation only. Please ask in the [forum](https://forum.k9mail.app/)
