### ISSUE TITLE
Write down step by step instructions on how to create screenshots

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail-docs#2]
Many of the documentation pages contain screenshots of the app. In order for the screenshots to have a uniform look we should use an emulator image with a specific configuration to create all screenshots.

The instructions could live in the [wiki](https://github.com/k9mail/k9mail-docs/wiki).

**Comment by artbristol** [comment]
The existing screenshots are a mixture of 480x800, 300x500, and 1440x2560. They'll all get redone anyway, so we don't have to match any of them.

I'm proposing to use 480x800 since:
* it'll be a good check that everything still works at a low resolution
* the help pages will download quicker especially over a mobile network

**Comment by cketti** [comment]
It would be nice if we used a rather large resolution for the emulator and then downscaled images for the documentation page (clicking the image could show the larger version). But I don't know if mkdocs supports something like that.

**Comment by artbristol** [comment]
I can't see anything like that, I tried the folllowing places

https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#images-tables-charts--graphs
https://python-markdown.github.io/extensions/
https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions

Shall I just do them in large resolution (1080x1920) and maybe later downscale them if time permits?

**Comment by cketti** [comment]
> Shall I just do them in large resolution (1080x1920) and maybe later downscale them if time permits?

Large resolution sounds good. We can figure out the downscaling later.
