### ISSUE TITLE
Update 'SSL / TLS' page

### ISSUE THREAD

**Issue by cketti** [k9mail/k9mail-docs#21]
This should be less of a wikipedia entry on TLS and more K-9 Mail specific. See [DefaultTrustedSocketFactory](https://github.com/k9mail/k-9/blob/db79174527edacc29bf1edf6b669d57851588804/mail/common/src/main/java/com/fsck/k9/mail/ssl/DefaultTrustedSocketFactory.java).

Maybe also include a link to the tables in the [`SSLSocket`](https://developer.android.com/reference/kotlin/javax/net/ssl/SSLSocket) documentation.

**Comment by artbristol** [comment]
Updated in the linked PR
