### ISSUE TITLE
Describe icon meanings

### ISSUE THREAD

**Issue by dilyanpalauzov** [k9mail/k9mail-docs#34]
When I select a message in K9 5.804 I see at the top four icons: trash, envelope, download (down-arrow) and folder.  

In the “Visible message actions” Display settings, I have selected only Delete and Move.

I clicked the download (down-arrow) icon and the message disappeared.

At https://k9mail.app/documentation/ there is no explanation what the icons mean.

I turn, I do not know what the icons mean (down-arrow) as example, but the icons are always present.

• Describe the meaning of icons in the message list, when a message is selected

**Comment by artbristol** [comment]
@dilyanpalauzov the icons are now described here https://docs.k9mail.app/en/current/reading/managing/; please close this issue if you are satisfied
