### ISSUE TITLE
K-9 requires password for OpenPGP using OpenKeyChain?

### ISSUE THREAD

**Issue by MrTAT2** [k9mail/k9mail-docs#93]
I'm new to this and not sure if this is normal behavior, but when I send an encrypted email using K-9 email (for Android), K-9 requires my password for my OpenPGP encryption key stored on OpenKeyChain.  K-9 will 'remember' the password with one of these three options: "until screen off", "for one hour", "for one day", or "until cleared".

Is this normal behavior for K9 to require the password be entered each and every time an encrypted email is sent with K9?

Hopefully I'm describing this correctly.  I just would like to know if I am supposed to enter my OpenPGP credentials each time an encrypted email is sent using K-9 email.  Thanks!

**Comment by cketti** [comment]
Please use the [forum](https://forum.k9mail.app/) for support requests.
