### ISSUE TITLE
Why is encryption not enabled by default?

### ISSUE THREAD

**Issue by hurzl** [k9mail/k9mail-docs#98]
When I start a new message to a person with known key, I get a disabled key lock and have to tap it to enable. Shouldn't it be enabled by default? I can't find a setting for this.

**Comment by cketti** [comment]
See https://k9mail.app/2018/02/26/OpenPGP-Considerations-Part-III-Autocrypt

In the future please use the [forum](https://forum.k9mail.app/) for support requests.

**Comment by hurzl** [comment]
https://github.com/thundernest/k-9/issues/2997#issuecomment-377727221
It is a security hole.
